---
driver:
  name: docker

provisioner:
  name: chef_zero

driver_config:
  use_sudo: false

platforms:
  - name: ubuntu-14.04
    driver_config:
      disable_upstart: false
      image: ubuntu-upstart:14.04
      run_command: /sbin/init
    run_list:
      - recipe[apt]
      - recipe[netstat]

suites:
  - name: standalone
    attributes:
      mw_mysql:
        max_connections: 10
        expire_logs_days: 5
    run_list:
      - recipe[mw_mysql]
  - name: cluster
    run_list:
      - recipe[integration_test::master_slave]
