name 'mw_mysql'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures mw_mysql'
long_description 'Installs/Configures mw_mysql'
version '0.1.3'

depends 'mysql', '~> 6.1.0'
depends 'mysql_tuning', '~> 0.4.0'
depends 'chef-sugar'
